;; -*- coding: utf-8-unix -*-
;; Automatically written history of nREPL session
;; Edit at your own risk

("(do (require 'www.server)
          (www.server/-main))" "(check-modal-open-close)" "(refresh)" "(check-modal-open-close)" "(check-display-name-change)" "(refresh)" "(check-display-name-change)" "(not (fn []))" "(not (fn ))" "(check-display-name-change)" "(wait-until (not #(visible? \"#display-name\")))" "(visible? \"#display-name\")" "(check-display-name-change)" "(do (refresh)
                                     (wait-until #(exists? \"#avatar-popover\")))" "(check-display-name-change)" "(refresh drive)" "(refresh)" "(check-display-name-change)" "(refresh)




























































" "(check-display-name-change)" "(check-modal-open)" "(check-display-name-change)" "(check-modal-close)" "(check-modal-open)" "(re-find #\"opened1\"
                 (attribute \"#avatar-popover\" :class))" "(re-find #\"opened\"
                 (attribute \"#avatar-popover\" :class))" "(check-modal-open)" "(check-resolved-count)" "(check-modal-open)




























































" "(check-resolved-count)" "(do (require 'www.server)
          (www.server/-main))" "(-main)" "(do (require 'www.server)
          (www.server/-main))" "(do ('require www.server)
          (www.server/-main))" "(do ('require www.server/-main)
          (www.server/-main))" "(do (require 'www.server/-main)
          (www.server/-main))" "(do (require' www.server/-main)
          (www.server/-main))")